/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.gestionBibliotheque.front;

import com.gestionBibliotheque.classe.Eleve;
import com.gestionBibliotheque.classe.Emprunter;
import com.gestionBibliotheque.classe.Livre;
import com.gestionBibliotheque.classe.Professeur;
import com.gestionBibliotheque.gestion.GestionEleve;
import com.gestionBibliotheque.gestion.GestionEmprunt;
import com.gestionBibliotheque.gestion.GestionLivre;
import com.gestionBibliotheque.gestion.GestionProfesseur;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author solofonirina
 */
public class NouveauEmprunt extends javax.swing.JDialog {
    GestionEleve ge = new GestionEleve();
    GestionEmprunt gem = new GestionEmprunt();
    GestionLivre gl = new GestionLivre();
    GestionProfesseur gp = new GestionProfesseur();
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    public String emprunteur;
    public String codeLivre;
    public String[] emprunteurGettedSplitted;
    public String[] livreGettedSplitted;
    public Boolean insertion = false;
    public Boolean testEmprunteur = false;
    public int idEmprunt;


    /**
     * Creates new form NouveauEmprunt
     */
    public NouveauEmprunt(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneMain = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtEmprunteur = new javax.swing.JTextField();
        paneRechercheEmprunteur = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listEmprunteur = new javax.swing.JList<>();
        txtLivre = new javax.swing.JTextField();
        paneRechercheLivre = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listLivre = new javax.swing.JList<>();
        dateDebut = new com.toedter.calendar.JDateChooser();
        dateFin = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtAnneeScolaire = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        classe1 = new javax.swing.JComboBox<>();
        classe2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        comboEmprunteur = new javax.swing.JComboBox<>();
        nombreLivre = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        paneMain.setBackground(new java.awt.Color(254, 254, 254));
        paneMain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                paneMainMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(14, 99, 254));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(254, 254, 254));
        jLabel9.setText("Nouveau emprunt");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel9)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(27, 27, 27))
        );

        txtEmprunteur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEmprunteurMouseClicked(evt);
            }
        });
        txtEmprunteur.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtEmprunteurKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmprunteurKeyReleased(evt);
            }
        });

        paneRechercheEmprunteur.setAlignmentX(0.0F);
        paneRechercheEmprunteur.setAlignmentY(0.0F);

        listEmprunteur.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listEmprunteur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listEmprunteurMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listEmprunteur);

        javax.swing.GroupLayout paneRechercheEmprunteurLayout = new javax.swing.GroupLayout(paneRechercheEmprunteur);
        paneRechercheEmprunteur.setLayout(paneRechercheEmprunteurLayout);
        paneRechercheEmprunteurLayout.setHorizontalGroup(
            paneRechercheEmprunteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        paneRechercheEmprunteurLayout.setVerticalGroup(
            paneRechercheEmprunteurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRechercheEmprunteurLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        txtLivre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtLivreMouseClicked(evt);
            }
        });
        txtLivre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLivreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLivreKeyReleased(evt);
            }
        });

        paneRechercheLivre.setAlignmentX(0.0F);
        paneRechercheLivre.setAlignmentY(0.0F);

        listLivre.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listLivre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listLivreMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listLivre);

        javax.swing.GroupLayout paneRechercheLivreLayout = new javax.swing.GroupLayout(paneRechercheLivre);
        paneRechercheLivre.setLayout(paneRechercheLivreLayout);
        paneRechercheLivreLayout.setHorizontalGroup(
            paneRechercheLivreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
        );
        paneRechercheLivreLayout.setVerticalGroup(
            paneRechercheLivreLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneRechercheLivreLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        dateDebut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateDebutMouseClicked(evt);
            }
        });
        dateDebut.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateDebutPropertyChange(evt);
            }
        });

        dateFin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dateFinMouseClicked(evt);
            }
        });
        dateFin.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dateFinPropertyChange(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(1, 1, 1));
        jLabel1.setText("Début :");

        jLabel2.setForeground(new java.awt.Color(1, 1, 1));
        jLabel2.setText("Fin :");

        jLabel3.setForeground(new java.awt.Color(1, 1, 1));
        jLabel3.setText("Emprunteur :");

        jLabel4.setForeground(new java.awt.Color(1, 1, 1));
        jLabel4.setText("Livre :");

        jLabel5.setForeground(new java.awt.Color(1, 1, 1));
        jLabel5.setText("Date d'emprunt :");

        txtAnneeScolaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAnneeScolaireMouseClicked(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(1, 1, 1));
        jLabel6.setText("Année scolaire :");

        jLabel7.setForeground(new java.awt.Color(1, 1, 1));
        jLabel7.setText("Classe :");

        classe1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "12", "11", "10", "9", "8", "7", "6", "5", "4", "3", "2", "1S", "1L", "TA", "TD", "TC" }));
        classe1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classe1MouseClicked(evt);
            }
        });

        classe2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "A", "B", "C", "1", "2" }));

        jButton1.setBackground(new java.awt.Color(14, 99, 254));
        jButton1.setForeground(new java.awt.Color(254, 254, 254));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestionBibliotheque/image/save.png"))); // NOI18N
        jButton1.setText("Sauvegarder");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(14, 99, 254));
        jButton2.setForeground(new java.awt.Color(254, 254, 254));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/gestionBibliotheque/image/Cancel.png"))); // NOI18N
        jButton2.setText("Annuler");

        comboEmprunteur.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir", "Elève", "Professeur" }));
        comboEmprunteur.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboEmprunteurItemStateChanged(evt);
            }
        });

        nombreLivre.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nombreLivreStateChanged(evt);
            }
        });
        nombreLivre.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nombreLivreInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                nombreLivreCaretPositionChanged(evt);
            }
        });
        nombreLivre.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                nombreLivrePropertyChange(evt);
            }
        });
        nombreLivre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreLivreKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                nombreLivreKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nombreLivreKeyReleased(evt);
            }
        });
        nombreLivre.addVetoableChangeListener(new java.beans.VetoableChangeListener() {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {
                nombreLivreVetoableChange(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(3, 3, 3));
        jLabel8.setText("Nombre livre emprunté :");

        javax.swing.GroupLayout paneMainLayout = new javax.swing.GroupLayout(paneMain);
        paneMain.setLayout(paneMainLayout);
        paneMainLayout.setHorizontalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(paneMainLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneMainLayout.createSequentialGroup()
                        .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneMainLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneMainLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(comboEmprunteur, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmprunteur, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paneMainLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(paneRechercheEmprunteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(paneRechercheLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMainLayout.createSequentialGroup()
                        .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneMainLayout.createSequentialGroup()
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneMainLayout.createSequentialGroup()
                                        .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(paneMainLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(97, 97, 97)))
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(txtAnneeScolaire, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paneMainLayout.createSequentialGroup()
                                .addComponent(classe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(classe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nombreLivre, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(51, 51, 51))
                    .addGroup(paneMainLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton1)
                        .addGap(62, 62, 62)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        paneMainLayout.setVerticalGroup(
            paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneMainLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmprunteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(comboEmprunteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paneMainLayout.createSequentialGroup()
                        .addComponent(paneRechercheEmprunteur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(paneMainLayout.createSequentialGroup()
                                .addComponent(paneRechercheLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(dateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(dateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addComponent(txtAnneeScolaire, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(classe1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classe2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreLivre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(34, 34, 34)
                .addGroup(paneMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(paneMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        paneRechercheEmprunteur.setVisible(false);
        paneRechercheLivre.setVisible(false);
        int dateNow = LocalDate.now().getYear();
        if(LocalDate.now().getMonth().getValue() <= 8){
            txtAnneeScolaire.setText((dateNow-1)+"-"+dateNow);
            idEmprunt = gem.newId();
        }else{
            txtAnneeScolaire.setText(dateNow+"-"+(dateNow+1));
            idEmprunt = gem.newId();
        }
    }//GEN-LAST:event_formWindowActivated

    private void txtEmprunteurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEmprunteurMouseClicked
        // TODO add your handling code here:
        if("Elève".equals(comboEmprunteur.getSelectedItem().toString())){
            paneRechercheEmprunteur.setVisible(true);
            Vector<String> v = new Vector<String>();
            for(Eleve e : ge.search(txtEmprunteur.getText())){
                v.add(e.getNumeroMatricule()+"-"+e.getNom());
            }
            listEmprunteur.setListData(v);
            paneRechercheLivre.setVisible(false);
        }else if("Professeur".equals(comboEmprunteur.getSelectedItem().toString())){
            paneRechercheEmprunteur.setVisible(true);
            Vector<String> v = new Vector<String>();
            for(Professeur p : gp.search(txtEmprunteur.getText())){
                v.add(p.getCodeProfesseur()+"-"+p.getNomProfesseur());
            }
            listEmprunteur.setListData(v);
            paneRechercheLivre.setVisible(false);
        }
    }//GEN-LAST:event_txtEmprunteurMouseClicked

    private void listEmprunteurMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listEmprunteurMouseClicked
        // TODO add your handling code here:
        paneRechercheEmprunteur.setVisible(false);
        txtEmprunteur.setText(listEmprunteur.getSelectedValue());
        emprunteurGettedSplitted = listEmprunteur.getSelectedValue().split("-");
        if("Professeur".equals(comboEmprunteur.getSelectedItem().toString())){
            if(gem.testEmprunteur(emprunteurGettedSplitted[0]+"-"+emprunteurGettedSplitted[1]) == 0){
               testEmprunteur = true;
            }else{
                testEmprunteur = false;
            }
        }else{
            if(gem.testEmprunteur(emprunteurGettedSplitted[0]) == 0){
                testEmprunteur = true;
            }else{
                testEmprunteur = false;
            }
        }
    }//GEN-LAST:event_listEmprunteurMouseClicked

    private void txtEmprunteurKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmprunteurKeyPressed
        // TODO add your handling code here:
        if("Elève".equals(comboEmprunteur.getSelectedItem().toString())){
            paneRechercheEmprunteur.setVisible(true);
            Vector<String> v = new Vector<String>();
            for(Eleve e : ge.search(txtEmprunteur.getText())){
                v.add(e.getNumeroMatricule()+"-"+e.getNom());
            }
            listEmprunteur.setListData(v);
            paneRechercheLivre.setVisible(false);
        }else if("Professeur".equals(comboEmprunteur.getSelectedItem().toString())){
            paneRechercheEmprunteur.setVisible(true);
            Vector<String> v = new Vector<String>();
            for(Professeur p : gp.search(txtEmprunteur.getText())){
                v.add(p.getCodeProfesseur()+"-"+p.getNomProfesseur());
            }
            listEmprunteur.setListData(v);
            paneRechercheLivre.setVisible(false);
        }
    }//GEN-LAST:event_txtEmprunteurKeyPressed

    private void txtLivreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLivreKeyPressed
        // TODO add your handling code here:
        paneRechercheLivre.setVisible(true);
        Vector<String> v = new Vector<String>();
        for(Livre l : gl.search(txtLivre.getText())){
            v.add(l.getCodeLivre()+"-"+l.getLibelleLivre());
        }
        listLivre.setListData(v);
        paneRechercheEmprunteur.setVisible(false);
    }//GEN-LAST:event_txtLivreKeyPressed

    private void txtLivreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtLivreMouseClicked
        // TODO add your handling code here:
        paneRechercheLivre.setVisible(true);
        Vector<String> v = new Vector<String>();
        for(Livre l : gl.search(txtLivre.getText())){
            v.add(l.getCodeLivre()+"-"+l.getLibelleLivre());
        }
        listLivre.setListData(v);
        paneRechercheEmprunteur.setVisible(false);
    }//GEN-LAST:event_txtLivreMouseClicked

    private void listLivreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listLivreMouseClicked
        // TODO add your handling code here:
        paneRechercheLivre.setVisible(false);
        txtLivre.setText(listLivre.getSelectedValue());
        livreGettedSplitted = listLivre.getSelectedValue().split("-");
        codeLivre = livreGettedSplitted[0]+"-"+livreGettedSplitted[1];
    }//GEN-LAST:event_listLivreMouseClicked

    private void txtEmprunteurKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmprunteurKeyReleased
        // TODO add your handling code here:
        if("Elève".equals(comboEmprunteur.getSelectedItem().toString())){
            paneRechercheEmprunteur.setVisible(true);
            Vector<String> v = new Vector<String>();
            for(Eleve e : ge.search(txtEmprunteur.getText())){
                v.add(e.getNumeroMatricule()+"-"+e.getNom());
            }
            listEmprunteur.setListData(v);
            paneRechercheLivre.setVisible(false);
        }else if("Professeur".equals(comboEmprunteur.getSelectedItem().toString())){
            paneRechercheEmprunteur.setVisible(true);
            Vector<String> v = new Vector<String>();
            for(Professeur p : gp.search(txtEmprunteur.getText())){
                v.add(p.getCodeProfesseur()+"-"+p.getNomProfesseur());
            }
            listEmprunteur.setListData(v);
            paneRechercheLivre.setVisible(false);
        }
    }//GEN-LAST:event_txtEmprunteurKeyReleased

    private void txtLivreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLivreKeyReleased
        // TODO add your handling code here:
        paneRechercheLivre.setVisible(true);
        Vector<String> v = new Vector<String>();
        for(Livre l : gl.search(txtLivre.getText())){
            v.add(l.getCodeLivre()+"-"+l.getLibelleLivre());
        }
        listLivre.setListData(v);
        paneRechercheEmprunteur.setVisible(false);
    }//GEN-LAST:event_txtLivreKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int nbLivreExistant = 0;
        int nbLivreEmprunter = 0;
        for(Livre l : gl.getLivreById(codeLivre)){
            nbLivreExistant = l.getNombreLivre();
        }
        nbLivreEmprunter = gem.getNombreLivre(codeLivre);
        insertion = !((nbLivreExistant-nbLivreEmprunter) < Integer.parseInt(nombreLivre.getValue().toString()) || Integer.parseInt(nombreLivre.getValue().toString())<0);
        
        if(dateDebut.getDate() == null || dateFin.getDate() == null || "".equals(txtLivre.getText())){
            if("".equals(txtLivre.getText())){
                JOptionPane.showMessageDialog(null, "Veuillez choisir un livre");
            }else if(dateDebut.getDate() == null){
                JOptionPane.showMessageDialog(null, "La date début ne peut pas être null");
            }else{
                JOptionPane.showMessageDialog(null, "La date fin ne peut pas être null");                
            }
        }else if("Choisir".equals(comboEmprunteur.getSelectedItem().toString())){
            JOptionPane.showMessageDialog(null, "Veuillez choisir l'emprunteur");
        }else if(!testEmprunteur){
            if(JOptionPane.showConfirmDialog(null, "Cet emprunteur n'a pas encore retourner un livre !, Voulez-vous continuer ?") == JOptionPane.YES_OPTION){
                if(!insertion){
                    if(Integer.parseInt(nombreLivre.getValue().toString())<0){
                        JOptionPane.showMessageDialog(null, "Le nombre du livre demandé doit être positif!");
                    }else{
                        JOptionPane.showMessageDialog(null, "Veuillez vérifier le nombre de livre disponible et le livre demandé !");                    
                    }
                }else{
                    if("Professeur".equals(comboEmprunteur.getSelectedItem().toString())){
                        gem.insert(new Emprunter(idEmprunt, emprunteurGettedSplitted[0]+"-"+emprunteurGettedSplitted[1], codeLivre, new java.sql.Date(dateDebut.getDate().getTime()), new java.sql.Date(dateFin.getDate().getTime()), classe1.getSelectedItem().toString()+" "+classe2.getSelectedItem().toString(), txtAnneeScolaire.getText(), Integer.parseInt(nombreLivre.getValue().toString()), "En cours"));
                        dispose();
                    }else{
                        if("  ".equals(classe1.getSelectedItem().toString()+classe2.getSelectedItem().toString())){
                            JOptionPane.showMessageDialog(null, "Veuillez choisir la classe !");
                        }else{
                            gem.insert(new Emprunter(idEmprunt, emprunteurGettedSplitted[0], codeLivre, new java.sql.Date(dateDebut.getDate().getTime()), new java.sql.Date(dateFin.getDate().getTime()), classe1.getSelectedItem().toString()+" "+classe2.getSelectedItem().toString(), txtAnneeScolaire.getText(), Integer.parseInt(nombreLivre.getValue().toString()), "En cours"));
                            dispose();
                        }
                    }
                } 
            }
        }else{
            if(!insertion){
                if(Integer.parseInt(nombreLivre.getValue().toString())<0){
                    JOptionPane.showMessageDialog(null, "Le nombre du livre demandé doit être positif!");
                }else{
                    JOptionPane.showMessageDialog(null, "Veuillez vérifier le nombre de livre disponible et le livre demandé !");                    
                }
            }else{
                if("Professeur".equals(comboEmprunteur.getSelectedItem().toString())){
                    gem.insert(new Emprunter(idEmprunt, emprunteurGettedSplitted[0]+"-"+emprunteurGettedSplitted[1], codeLivre, new java.sql.Date(dateDebut.getDate().getTime()), new java.sql.Date(dateFin.getDate().getTime()), classe1.getSelectedItem().toString()+" "+classe2.getSelectedItem().toString(), txtAnneeScolaire.getText(), Integer.parseInt(nombreLivre.getValue().toString()), "En cours"));
                    dispose();
                }else{
                    if("  ".equals(classe1.getSelectedItem().toString()+classe2.getSelectedItem().toString())){
                        JOptionPane.showMessageDialog(null, "Veuillez choisir la classe !");
                    }else{
                        gem.insert(new Emprunter(idEmprunt, emprunteurGettedSplitted[0], codeLivre, new java.sql.Date(dateDebut.getDate().getTime()), new java.sql.Date(dateFin.getDate().getTime()), classe1.getSelectedItem().toString()+" "+classe2.getSelectedItem().toString(), txtAnneeScolaire.getText(), Integer.parseInt(nombreLivre.getValue().toString()), "En cours"));
                        dispose();
                    }
                }
            } 
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboEmprunteurItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboEmprunteurItemStateChanged
        // TODO add your handling code here:
        emprunteur = comboEmprunteur.getSelectedItem().toString();
        txtEmprunteur.setText("");
    }//GEN-LAST:event_comboEmprunteurItemStateChanged

    private void nombreLivreStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nombreLivreStateChanged
        // TODO add your handling code here:
//        int nbLivreExistant = 0;
//        int nbLivreEmprunter = 0;
//        for(Livre l : gl.getLivreById(codeLivre)){
//            nbLivreExistant = l.getNombreLivre();
//        }
//        nbLivreEmprunter = gem.getNombreLivre(codeLivre);
//        if((nbLivreExistant-nbLivreEmprunter) < Integer.parseInt(nombreLivre.getValue().toString()) || Integer.parseInt(nombreLivre.getValue().toString())<0){
//            insertion = false;
//        }else{            
//            insertion = true;
//        }
    }//GEN-LAST:event_nombreLivreStateChanged

    private void nombreLivreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreLivreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreLivreKeyPressed

    private void nombreLivreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreLivreKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreLivreKeyReleased

    private void nombreLivreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreLivreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreLivreKeyTyped

    private void nombreLivrePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_nombreLivrePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreLivrePropertyChange

    private void nombreLivreVetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException {//GEN-FIRST:event_nombreLivreVetoableChange
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreLivreVetoableChange

    private void nombreLivreInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nombreLivreInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreLivreInputMethodTextChanged

    private void nombreLivreCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nombreLivreCaretPositionChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreLivreCaretPositionChanged

    private void paneMainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paneMainMouseClicked
        // TODO add your handling code here:
        paneRechercheEmprunteur.setVisible(false);
        paneRechercheLivre.setVisible(false);
    }//GEN-LAST:event_paneMainMouseClicked

    private void dateDebutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateDebutMouseClicked
        // TODO add your handling code here:
        paneRechercheEmprunteur.setVisible(false);
        paneRechercheLivre.setVisible(false);
    }//GEN-LAST:event_dateDebutMouseClicked

    private void dateFinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dateFinMouseClicked
        // TODO add your handling code here:
        paneRechercheEmprunteur.setVisible(false);
        paneRechercheLivre.setVisible(false);
//        System.out.println(dateFin.getDate());
    }//GEN-LAST:event_dateFinMouseClicked

    private void txtAnneeScolaireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAnneeScolaireMouseClicked
        // TODO add your handling code here:
        paneRechercheEmprunteur.setVisible(false);
        paneRechercheLivre.setVisible(false);
    }//GEN-LAST:event_txtAnneeScolaireMouseClicked

    private void classe1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classe1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_classe1MouseClicked

    private void dateFinPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateFinPropertyChange
        // TODO add your handling code here:
        java.util.Date utilDateD = dateDebut.getDate();
        java.util.Date utilDateF = dateFin.getDate();

        if(utilDateD != null && utilDateF != null) {
            java.sql.Date dateD = new java.sql.Date(utilDateD.getTime());
            java.sql.Date dateF = new java.sql.Date(utilDateF.getTime());

            if(dateD.after(dateF)) {
                JOptionPane.showMessageDialog(null, "La date début ne doit pas être postérieure à la date fin");
                dateFin.setDate(null);
            }
        }
    }//GEN-LAST:event_dateFinPropertyChange

    private void dateDebutPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dateDebutPropertyChange
        // TODO add your handling code here:
        java.util.Date utilDateD = dateDebut.getDate();
        java.util.Date utilDateF = dateFin.getDate();

        if(utilDateD != null && utilDateF != null) {
            java.sql.Date dateD = new java.sql.Date(utilDateD.getTime());
            java.sql.Date dateF = new java.sql.Date(utilDateF.getTime());

            if(dateD.after(dateF)) {
                JOptionPane.showMessageDialog(null, "La date début ne doit pas être postérieure à la date fin");
                dateDebut.setDate(null);
            }
        }
    }//GEN-LAST:event_dateDebutPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NouveauEmprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NouveauEmprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NouveauEmprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NouveauEmprunt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                NouveauEmprunt dialog = new NouveauEmprunt(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> classe1;
    private javax.swing.JComboBox<String> classe2;
    private javax.swing.JComboBox<String> comboEmprunteur;
    private com.toedter.calendar.JDateChooser dateDebut;
    private com.toedter.calendar.JDateChooser dateFin;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listEmprunteur;
    private javax.swing.JList<String> listLivre;
    private javax.swing.JSpinner nombreLivre;
    private javax.swing.JPanel paneMain;
    private javax.swing.JPanel paneRechercheEmprunteur;
    private javax.swing.JPanel paneRechercheLivre;
    private javax.swing.JTextField txtAnneeScolaire;
    private javax.swing.JTextField txtEmprunteur;
    private javax.swing.JTextField txtLivre;
    // End of variables declaration//GEN-END:variables
}
